SELECT 
    COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_SCHEMA = DATABASE() -- Use the current database passed as an argument
    AND TABLE_NAME = 'Books';
    COLUMN_TYPE", "TABLE_SCHEMA = 'alx_book_store'